# Generated by Django 5.2.11 on 2026-03-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dd_pbg',
            field=models.CharField(blank=True, help_text='DD/PBG type (Demand Draft / Performance Bank Guarantee)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='emd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Earnest Money Deposit amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='emd_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='emd_return_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='emd_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tender_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(blank=True, choices=[('BUDGETARY', 'Budgetary'), ('FIRM', 'Firm'), ('BID', 'Bid'), ('PURCHASE', 'Purchase'), ('NEGOTIATION', 'Negotiation'), ('TENDER', 'Tender')], max_length=20),
        ),
    ]
