# Generated by Django 5.2.11 on 2026-06-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options'),
        ('enquiries', '0002_enquiry_dd_pbg_enquiry_emd_amount_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDelayReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.CharField(choices=[('NEW', 'New Enquiry'), ('NEGOTIATION', 'Under Negotiation'), ('PO_RECEIVED', 'PO Received'), ('LOST', 'Enquiry Lost'), ('REGRET', 'Regret')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='changed_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Stores which fields were changed'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_latest_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='parent_enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='enquiries.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='revision_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='Reason for this revision'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['enquiry_number', 'is_latest_revision'], name='enquiries_e_enquiry_1dfd96_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['parent_enquiry', 'revision_number'], name='enquiries_e_parent__78ff3c_idx'),
        ),
        migrations.AddField(
            model_name='enquirydelayreason',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_reasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirydelayreason',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reasons', to='enquiries.enquiry'),
        ),
    ]
