# Generated by Django 5.2.11 on 2026-03-26 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oa_number', models.CharField(max_length=50, unique=True)),
                ('billing_snapshot', models.JSONField(blank=True, null=True)),
                ('shipping_snapshot', models.JSONField(blank=True, null=True)),
                ('transport_details', models.JSONField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oa', to='quotations.quotation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('HOLD', 'Hold'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('stage', models.CharField(choices=[('PLANNING', 'Planning'), ('ENGINEERING', 'Engineering'), ('PRODUCTION', 'Production'), ('QA', 'QA'), ('DISPATCH', 'Dispatch')], default='PLANNING', max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
                ('oa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.orderacknowledgement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OALineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=100)),
                ('customer_part_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('oa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.orderacknowledgement')),
            ],
        ),
        migrations.CreateModel(
            name='OACommercialTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(blank=True, max_length=150)),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_after_invoicing', models.PositiveIntegerField(default=0)),
                ('price_basis', models.CharField(blank=True, max_length=100)),
                ('insurance', models.CharField(blank=True, max_length=100)),
                ('inspection', models.CharField(blank=True, max_length=100)),
                ('ld_clause', models.CharField(blank=True, max_length=100)),
                ('test_certificate', models.CharField(blank=True, max_length=100)),
                ('warranty', models.CharField(blank=True, max_length=255)),
                ('drawing_approval', models.CharField(blank=True, max_length=100)),
                ('freight_charges', models.CharField(blank=True, max_length=150)),
                ('abg_format', models.CharField(blank=True, max_length=100)),
                ('pbg_format', models.CharField(blank=True, max_length=100)),
                ('sd_format', models.CharField(blank=True, max_length=100)),
                ('dispatch_clearance', models.CharField(blank=True, max_length=100)),
                ('commissioning_support', models.CharField(blank=True, max_length=150)),
                ('schedule_dispatch_date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('channel_partner_name', models.CharField(blank=True, max_length=255)),
                ('consultant_name', models.CharField(blank=True, max_length=255)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultant_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('oa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_terms', to='orders.orderacknowledgement')),
            ],
        ),
    ]
