# Generated by Django 5.2.11 on 2026-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('PARTIALLY_INVOICED', 'Partially Invoiced'), ('FULLY_INVOICED', 'Fully Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_category',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International / Export')], default='DOMESTIC', max_length=20),
        ),
    ]
