# Generated by Django 5.2.11 on 2026-03-26 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('valid_till_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=20)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20)),
                ('client_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_CLIENT', 'Rejected By Client')], default='DRAFT', max_length=30)),
                ('manager_remark', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='enquiries.enquiry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotation_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=100)),
                ('customer_part_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('description_snapshot', models.TextField(blank=True)),
                ('hsn_snapshot', models.CharField(blank=True, max_length=50)),
                ('unit_snapshot', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.TextField(blank=True)),
                ('sales_tax', models.CharField(blank=True, max_length=100)),
                ('excise_duty', models.CharField(blank=True, max_length=100)),
                ('warranty', models.TextField(blank=True)),
                ('packing_forwarding', models.CharField(blank=True, max_length=100)),
                ('price_basis', models.CharField(blank=True, max_length=100)),
                ('insurance', models.CharField(blank=True, max_length=100)),
                ('freight', models.CharField(blank=True, max_length=100)),
                ('delivery', models.TextField(blank=True)),
                ('validity', models.TextField(blank=True)),
                ('decision_expected', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='quotations.quotation')),
            ],
        ),
    ]
