# Generated by Django 5.2.11 on 2026-06-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_engineeringbom_bomline_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bom_reference',
        ),
        migrations.AddField(
            model_name='project',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='engineering.engineeringbom'),
        ),
    ]
