# Generated by Django 5.2.11 on 2026-07-10 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_engineeringpackage_engineeringpackagechangenotice_and_more'),
        ('projects', '0002_remove_project_bom_reference_project_bom'),
        ('purchase', '0003_purchaseindent_project_purchaseindentitem_mrp_line_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bom',
        ),
        migrations.AddField(
            model_name='project',
            name='active_package',
            field=models.ForeignKey(blank=True, help_text='The currently accepted engineering package for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_projects', to='engineering.engineeringpackage'),
        ),
        migrations.CreateModel(
            name='ProjectMaterialRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('purchased_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('RESERVED', 'Reserved'), ('PURCHASED', 'Purchased'), ('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='REQUIRED', max_length=20)),
                ('procurement_type', models.CharField(choices=[('STOCK', 'Stock Item'), ('PURCHASE', 'Purchase External'), ('MANUFACTURE', 'Manufacture In-House')], default='PURCHASE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_requirement', models.ForeignKey(blank=True, help_text='The engineering package that created this requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requirements', to='engineering.engineeringpackage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('indent_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requirements', to='purchase.purchaseindentitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_material_requirements', to='engineering.engineeringitemmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='projects.project')),
            ],
            options={
                'ordering': ['required_by', 'item__item_code'],
                'unique_together': {('project', 'item')},
            },
        ),
    ]
