# Generated by Django 5.2.11 on 2026-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company_name']},
        ),
    ]
