# Generated by Django 5.2.11 on 2026-06-18 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineering', '0002_engineeringbom_bomline_and_more'),
        ('inventory', '0003_materialissueslip_project_and_more'),
        ('projects', '0001_initial'),
        ('purchase', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.CharField(blank=True, help_text='Auto-generated: MRP-PRJ-2026-0001-001', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_items', models.IntegerField(default=0)),
                ('items_with_shortage', models.IntegerField(default=0)),
                ('total_shortage_value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost of all shortages', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(help_text='BOM version used for this MRP run', on_delete=django.db.models.deletion.PROTECT, related_name='mrp_runs', to='engineering.engineeringbom')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_runs', to='projects.project')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='MRPLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1)),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('uom', models.CharField(max_length=20)),
                ('available_qty', models.DecimalField(decimal_places=3, default=0, help_text='Stock available at time of MRP run (QC PASSED)', max_digits=15)),
                ('on_order_qty', models.DecimalField(decimal_places=3, default=0, help_text='Quantity already on open POs', max_digits=15)),
                ('shortage_qty', models.DecimalField(decimal_places=3, default=0, help_text='required - available - on_order (if positive)', max_digits=15)),
                ('has_shortage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted to Indent'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('indent_raised', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True, help_text='System recommendation for procurement')),
                ('bom_path', models.TextField(blank=True, help_text='Hierarchical path: SWAS Panel > Analyzer Rack > Analyser')),
                ('depth', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineering_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_lines', to='engineering.engineeringitemmaster')),
                ('indent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_lines', to='purchase.purchaseindent')),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Linked inventory item (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_lines', to='inventory.itemmaster')),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mrp.mrprun')),
            ],
            options={
                'ordering': ['-has_shortage', 'engineering_item__item_class', 'engineering_item__item_code'],
            },
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['project', 'status'], name='mrp_mrprun_project_cf54c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['run_at'], name='mrp_mrprun_run_at_97be41_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpline',
            index=models.Index(fields=['mrp_run', 'has_shortage'], name='mrp_mrpline_mrp_run_3b0d69_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpline',
            index=models.Index(fields=['mrp_run', 'indent_raised'], name='mrp_mrpline_mrp_run_61be0c_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpline',
            index=models.Index(fields=['engineering_item', 'mrp_run'], name='mrp_mrpline_enginee_871c8a_idx'),
        ),
    ]
