# Generated by Django 5.2.11 on 2026-06-18 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringItemMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, help_text='Auto-generated: ENG-00001', max_length=30)),
                ('name', models.CharField(help_text='Engineering name / description', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_class', models.CharField(choices=[('A', 'Class A - High Value (70-80% of spend)'), ('B', 'Class B - Medium Value (15-20% of spend)'), ('C', 'Class C - Low Value / Consumables')], default='B', help_text='A=High Value, B=Medium, C=Low Value/Consumable', max_length=1)),
                ('category', models.CharField(blank=True, help_text='e.g. Instrumentation, Electrical, Mechanical', max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('drawing_number', models.CharField(blank=True, help_text='Primary drawing reference number', max_length=100)),
                ('current_revision', models.CharField(blank=True, help_text='Current active revision (e.g. Rev C)', max_length=10)),
                ('specification', models.TextField(blank=True, help_text='Technical specification text')),
                ('make', models.CharField(blank=True, help_text='Preferred manufacturer brand', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Model / part number from manufacturer', max_length=100)),
                ('manufacturer_part_number', models.CharField(blank=True, help_text='MPN', max_length=100)),
                ('customer_part_number', models.CharField(blank=True, help_text='CPN - Customer-assigned part number', max_length=100)),
                ('uom', models.CharField(help_text='Unit of measure for engineering calculations', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engineering_items', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.OneToOneField(blank=True, help_text='Link to Inventory Item Master (created by Stores when procurement needed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_item', to='inventory.itemmaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringItemRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(help_text='Revision identifier (e.g. Rev A, Rev B, Rev C)', max_length=10)),
                ('drawing_number', models.CharField(blank=True, help_text='Drawing number at this revision', max_length=100)),
                ('specification', models.TextField(blank=True, help_text='Spec at this revision - full snapshot')),
                ('change_description', models.TextField(blank=True, help_text='What changed vs. previous revision')),
                ('effective_date', models.DateField(help_text='Date this revision becomes effective')),
                ('obsoleted_date', models.DateField(blank=True, help_text='Set when superseded by next revision', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Only one revision per item should be current')),
                ('document', models.FileField(blank=True, help_text='Drawing PDF or spec document for this revision', null=True, upload_to='engineering/revisions/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='engineering.engineeringitemmaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('DRAWING', 'Engineering Drawing'), ('SPEC', 'Specification'), ('DATASHEET', 'Technical Datasheet'), ('CERTIFICATE', 'Test Certificate / Calibration'), ('MANUAL', 'User Manual'), ('OTHER', 'Other Document')], default='DRAWING', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload the document file', upload_to='engineering/documents/%Y/%m/')),
                ('version', models.CharField(blank=True, help_text='Document version (if different from revision)', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='engineering.engineeringitemmaster')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='engineering.engineeringitemrevision')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engineeringitemmaster',
            index=models.Index(fields=['tenant', 'item_class'], name='engineering_tenant__7256d9_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringitemmaster',
            index=models.Index(fields=['tenant', 'category'], name='engineering_tenant__b2d820_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringitemmaster',
            index=models.Index(fields=['tenant', 'is_active'], name='engineering_tenant__31f0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringitemmaster',
            index=models.Index(fields=['drawing_number'], name='engineering_drawing_508011_idx'),
        ),
        migrations.AddConstraint(
            model_name='engineeringitemmaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_code'), name='unique_eng_item_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='engineeringitemrevision',
            constraint=models.UniqueConstraint(fields=('item', 'revision'), name='unique_revision_per_item'),
        ),
        migrations.AddConstraint(
            model_name='engineeringitemrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('item',), name='unique_current_revision_per_item'),
        ),
    ]
