# Generated by Django 5.2.11 on 2026-06-18 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_number', models.CharField(blank=True, help_text='Auto-generated: BOM-2026-0001', max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. SWAS Panel BOM', max_length=255)),
                ('version', models.CharField(help_text='BOM Rev A, BOM Rev B ...', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(help_text='Date this BOM version is valid from')),
                ('obsolete_date', models.DateField(blank=True, help_text='Set when superseded', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active BOM per parent_item at a time')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('parent_item', models.ForeignKey(help_text='The finished product / top-level assembly', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='engineering.engineeringitemmaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity per parent assembly', max_digits=15)),
                ('uom', models.CharField(help_text='Unit of measure', max_length=20)),
                ('item_class', models.CharField(blank=True, choices=[('A', 'Class A - High Value (70-80% of spend)'), ('B', 'Class B - Medium Value (15-20% of spend)'), ('C', 'Class C - Low Value / Consumables')], help_text='Denormalized from item for fast MRP', max_length=1)),
                ('reference_designator', models.CharField(blank=True, help_text='e.g. PLC-001, V-003 (from engineering drawing)', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Engineering notes / substitution info')),
                ('is_phantom', models.BooleanField(default=False, help_text='Phantom assemblies are exploded through, not procured')),
                ('effective_date', models.DateField(blank=True, help_text='Override BOM-level effective date', null=True)),
                ('obsolete_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='engineering.engineeringitemmaster')),
                ('parent_line', models.ForeignKey(blank=True, help_text='NULL = top-level component', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='engineering.bomline')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='engineering.engineeringbom')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='engineeringbom',
            index=models.Index(fields=['parent_item', 'is_active'], name='engineering_parent__029151_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringbom',
            index=models.Index(fields=['status'], name='engineering_status_ad457b_idx'),
        ),
        migrations.AddConstraint(
            model_name='engineeringbom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parent_item',), name='unique_active_bom_per_parent'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom', 'parent_line'], name='engineering_bom_id_6e44c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['item'], name='engineering_item_id_dc9da9_idx'),
        ),
    ]
