# Generated by Django 5.2.11 on 2026-07-10 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_engineeringbom_bomline_and_more'),
        ('projects', '0002_remove_project_bom_reference_project_bom'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_number', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bom_snapshot', models.JSONField(default=dict, help_text='Full BOM snapshot with all components (frozen on release)')),
                ('version', models.CharField(help_text='Package version (e.g., v1.0, v2.0)', max_length=10)),
                ('document_snapshots', models.JSONField(default=list, help_text='Frozen document snapshots')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('RELEASED', 'Released'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('change_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_packages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_package', models.ForeignKey(blank=True, help_text='Previous version of this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_package', to='engineering.engineeringpackage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_packages', to='projects.project')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_packages', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_packages', to=settings.AUTH_USER_MODEL)),
                ('source_bom', models.ForeignKey(blank=True, help_text='Original BOM this was created from (for traceability)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='engineering.engineeringbom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringPackageChangeNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecn_number', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField(help_text='Why is this change needed?')),
                ('impact_analysis', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEFERRED', 'Deferred')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ecns', to=settings.AUTH_USER_MODEL)),
                ('new_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superseding_notices', to='engineering.engineeringpackage')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notices', to='engineering.engineeringpackage')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ecns', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ecns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringPackageDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('DRAWING', 'Engineering Drawing'), ('SPEC', 'Specification'), ('DATASHEET', 'Technical Datasheet'), ('CERTIFICATE', 'Test Certificate / Calibration'), ('MANUAL', 'User Manual'), ('OTHER', 'Other Document')], default='DRAWING', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_links', to='engineering.engineeringdocument')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='engineering.engineeringpackage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PackageHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='engineering.engineeringpackage')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engineeringpackage',
            index=models.Index(fields=['project', 'status'], name='engineering_project_e6d862_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringpackage',
            index=models.Index(fields=['status', 'released_at'], name='engineering_status_7f8266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='engineeringpackage',
            unique_together={('project', 'version')},
        ),
    ]
