# Generated by Django 5.2.11 on 2026-03-26 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proforma_number', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('ff_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ff_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProformaLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=100)),
                ('customer_part_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proforma.proformainvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='proforma.proformainvoice')),
            ],
        ),
    ]
