# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_category', models.CharField(blank=True, help_text='Category-level plan. Used when no item-specific plan exists.', max_length=100)),
                ('qc_type', models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('IN_PROCESS', 'In-Process'), ('FINAL', 'Final / Pre-Dispatch'), ('RETURN', 'Customer Return')], default='INWARD', max_length=15)),
                ('sampling_type', models.CharField(choices=[('HUNDRED_PCT', '100% Inspection'), ('AQL', 'AQL Sampling'), ('SKIP_LOT', 'Skip-Lot')], default='HUNDRED_PCT', max_length=15)),
                ('aql_level', models.CharField(blank=True, help_text='AQL level e.g. II, S-1, S-2 (only for AQL sampling)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, help_text='Item-level plan. Takes priority over category plan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plans', to='inventory.itemmaster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['item_category', 'qc_type'],
            },
        ),
        migrations.CreateModel(
            name='InspectionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=150)),
                ('parameter_type', models.CharField(choices=[('VISUAL', 'Visual'), ('DIMENSIONAL', 'Dimensional'), ('FUNCTIONAL', 'Functional'), ('DOCUMENT', 'Document Check'), ('CHEMICAL', 'Chemical / Composition')], max_length=15)),
                ('acceptance_criteria', models.TextField(blank=True, help_text="Text description e.g. 'No visible scratches'")),
                ('measurement_unit', models.CharField(blank=True, max_length=30)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(default=0, help_text='Display/execution order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='qc.inspectionplan')),
            ],
            options={
                'ordering': ['sequence', 'parameter_name'],
            },
        ),
        migrations.CreateModel(
            name='QCInspectionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qc_number', models.CharField(blank=True, max_length=20)),
                ('qc_type', models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('IN_PROCESS', 'In-Process'), ('FINAL', 'Final / Pre-Dispatch'), ('RETURN', 'Customer Return')], max_length=15)),
                ('reference_type', models.CharField(help_text='GRN / PRODUCTION_STAGE / DISPATCH / RETURN', max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('outcome', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('HOLD', 'Hold')], max_length=5, null=True)),
                ('sample_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('inspected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('passed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('failed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_orders', to='inventory.stockbatch')),
                ('grn_item', models.ForeignKey(blank=True, help_text='Set for INWARD QC only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_orders', to='purchase.grnitem')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_orders', to='inventory.itemmaster')),
                ('plan', models.ForeignKey(blank=True, help_text='Auto-resolved; null if no matching plan found.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.inspectionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qc_attachments/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='qc.qcinspectionorder')),
            ],
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ncr_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('RETURN_TO_VENDOR', 'Return to Vendor'), ('SCRAP', 'Scrap'), ('REWORK', 'Rework'), ('ACCEPT_DEVIATION', 'Accept with Deviation')], max_length=20)),
                ('disposition_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_ncrs', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_ncrs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
                ('inspection_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='qc.qcinspectionorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.CharField(help_text="Flexible: '12.3' or 'PASS' or 'No scratches'", max_length=200)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'Not Applicable')], max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('inspection_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qc.qcinspectionorder')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.inspectionparameter')),
            ],
            options={
                'ordering': ['parameter__sequence'],
            },
        ),
    ]
