# Generated by Django 5.2.11 on 2026-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_bank_details_to_tenantletterhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantletterhead',
            name='accent_color',
            field=models.CharField(default='#122C41', help_text='Hex colour for table headers, e.g. #122C41', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenantletterhead',
            name='company_state',
            field=models.CharField(blank=True, help_text='Used to determine CGST/SGST (intra-state) vs IGST (inter-state).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantletterhead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantletterhead',
            name='letterhead_pdf',
            field=models.FileField(blank=True, help_text="Blank A4 PDF with the company's pre-designed stationery. Header must fit within the top 45 mm; footer within the bottom 28 mm. Leave the middle of each page white/empty.", null=True, upload_to='letterheads/pdfs/'),
        ),
    ]
