# Generated by Django 5.2.11 on 2026-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_tenantletterhead_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantletterhead',
            name='company_city',
            field=models.CharField(blank=True, help_text='Required for e-invoice generation (IRP SellerDtls.Loc).', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantletterhead',
            name='company_pincode',
            field=models.CharField(blank=True, help_text='6-digit PIN code. Required for e-invoice generation (IRP SellerDtls.Pin).', max_length=6),
        ),
    ]
