# Generated by Django 5.2.11 on 2026-04-22 07:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_invoice_status_order_order_category'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packing_list_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('no_of_packages', models.IntegerField(default=0)),
                ('consignee_name', models.CharField(blank=True, max_length=255)),
                ('consignee_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('packaging_type', models.CharField(blank=True, max_length=100)),
                ('packaging_case_no', models.CharField(blank=True, max_length=100)),
                ('packaging_dimension', models.CharField(blank=True, max_length=100)),
                ('dimension_metric', models.CharField(blank=True, max_length=20)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight_metric', models.CharField(blank=True, max_length=20)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight_metric', models.CharField(blank=True, max_length=20)),
                ('packing_list_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('packaging_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.packagingslip')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('amd_number', models.CharField(blank=True, max_length=100)),
                ('amd_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('invoice_type', models.CharField(blank=True, max_length=100)),
                ('bill_to', models.JSONField(blank=True, null=True)),
                ('ship_to', models.JSONField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('consignee_gst', models.CharField(blank=True, max_length=20)),
                ('consignor_gst', models.CharField(blank=True, max_length=20)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('date_of_removal', models.DateField(blank=True, null=True)),
                ('time_of_removal', models.TimeField(blank=True, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=100)),
                ('transporter', models.CharField(blank=True, max_length=255)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('lr_number', models.CharField(blank=True, max_length=100)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='packagingslip',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_slip', to='logistics.salesinvoice'),
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('challan_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True)),
                ('bill_to', models.JSONField(blank=True, null=True)),
                ('ship_to', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challan', to='logistics.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=100)),
                ('customer_part_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='logistics.salesinvoice')),
            ],
        ),
    ]
