# Generated by Django 5.2.11 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='state_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
