# Generated by Django 5.2.11 on 2026-04-23 09:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_salesinvoice_state_code'),
        ('orders', '0002_order_invoice_status_order_order_category'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='challan_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('back_order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('expected_dispatch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_order', to='logistics.salesinvoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_orders', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
