# Generated by Django 5.2.11 on 2026-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_deliverychallan_challan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='backorder',
            name='etd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backorder',
            name='tracking_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backorder',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('RETURNED', 'Returned')], default='IN_TRANSIT', max_length=20),
        ),
    ]
