# Generated by Django 5.2.11 on 2026-05-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_backorder_current_location_backorder_etd_and_more'),
        ('orders', '0002_order_invoice_status_order_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backorder',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='backorder',
            name='tracking_status',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='back_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='logistics.backorder'),
        ),
        migrations.AlterField(
            model_name='backorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BackOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=100)),
                ('customer_part_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity_dispatching', models.DecimalField(decimal_places=2, max_digits=10)),
                ('back_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='logistics.backorder')),
                ('oa_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='orders.oalineitem')),
            ],
            options={
                'unique_together': {('back_order', 'oa_line_item')},
            },
        ),
    ]
