# Generated by Django 5.2.11 on 2026-05-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_backorder_invoice_and_more'),
        ('orders', '0002_order_invoice_status_order_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoicelineitem',
            name='oa_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='orders.oalineitem'),
        ),
    ]
