# Generated by Django 5.2.11 on 2026-05-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_add_oa_line_item_to_invoice_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
    ]
