# Generated by Django 5.2.11 on 2026-05-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_backorder_tracking_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irn', models.CharField(blank=True, help_text='Invoice Reference Number — 64-char hash returned by IRP.', max_length=64)),
                ('ack_no', models.CharField(blank=True, help_text='Acknowledgement number from IRP.', max_length=20)),
                ('ack_date', models.DateTimeField(blank=True, help_text='Acknowledgement datetime from IRP (IST).', null=True)),
                ('signed_qr_data', models.TextField(blank=True, help_text='Base64/JWT signed QR string returned by IRP. Use this to render the QR code.')),
                ('signed_invoice', models.JSONField(blank=True, help_text='Complete SignedInvoice JSON as returned by IRP.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('request_payload', models.JSONField(blank=True, help_text='Exact JSON payload submitted to GSP/IRP.', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Complete JSON response from GSP/IRP.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable error if status=FAILED.')),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancel_remarks', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='einvoice', to='logistics.salesinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einvoices', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'E-Invoice Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantGSPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsp_provider', models.CharField(choices=[('NIC_SANDBOX', 'NIC Sandbox (testing)'), ('NIC_PROD', 'NIC Production'), ('MASTERS', 'Masters India'), ('CLEAR', 'ClearTax / Clear'), ('GENERIC', 'Generic GSP (custom base URL)')], default='NIC_SANDBOX', help_text='Which GSP / IRP endpoint to use.', max_length=20)),
                ('gsp_base_url', models.URLField(blank=True, help_text='Leave blank for known providers. Required only when gsp_provider is GENERIC.')),
                ('gstin', models.CharField(help_text='15-character GSTIN of the supplier.', max_length=15)),
                ('client_id', models.CharField(blank=True, help_text='GSP API client_id (issued by your GSP).', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='GSP API client_secret (issued by your GSP). Store encrypted in production.', max_length=255)),
                ('irp_username', models.CharField(blank=True, max_length=255)),
                ('irp_password', models.CharField(blank=True, help_text='IRP portal password. Store encrypted in production.', max_length=255)),
                ('_auth_token', models.TextField(blank=True, db_column='auth_token')),
                ('_token_expires', models.DateTimeField(blank=True, db_column='token_expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gsp_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant GSP Config',
            },
        ),
    ]
