# Generated by Django 5.2.11 on 2026-05-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reports', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='If True, all tenant users can view and run this report.'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
    ]
