# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssueSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slip_number', models.CharField(blank=True, help_text='Auto-generated: ISS00001', max_length=20)),
                ('job_order_ref', models.CharField(blank=True, help_text='Production job order reference (future module placeholder).', max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit at time of receipt (FIFO) or current weighted average.', max_digits=15)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('PENDING', 'Pending QC'), ('PASSED', 'QC Passed'), ('FAILED', 'QC Failed'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=10)),
            ],
            options={
                'ordering': ['received_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('ISSUE_TO_PRODUCTION', 'Issue to Production'), ('DISPATCH_TO_CUSTOMER', 'Dispatch to Customer'), ('JOB_WORK_OUT', 'Job Work Out'), ('JOB_WORK_IN', 'Job Work In'), ('TRANSFER', 'Warehouse Transfer'), ('ADJUSTMENT', 'Stock Adjustment'), ('OPENING', 'Opening Stock'), ('QC_REJECTION', 'QC Rejection'), ('RETURN_FROM_VENDOR', 'Return to Vendor')], max_length=30)),
                ('reference_type', models.CharField(blank=True, help_text='GRN / ISSUE_SLIP / TRANSFER / ADJUSTMENT etc.', max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('qty_in', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('qty_out', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, help_text='e.g. A, B, C', max_length=10)),
                ('rack', models.CharField(blank=True, help_text='e.g. 01, 02', max_length=10)),
                ('shelf', models.CharField(blank=True, help_text='e.g. 01, 02, 03', max_length=10)),
                ('bin_code', models.CharField(blank=True, help_text='Auto-composed: WH1-A-02-03', max_length=50)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bin_code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, help_text='Auto-generated: ITM00001', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('SEMI_FINISHED', 'Semi-Finished'), ('FINISHED', 'Finished Good'), ('CONSUMABLE', 'Consumable'), ('SPARE', 'Spare Part'), ('ASSEMBLY', 'Assembly / Sub-Assembly')], default='RAW_MATERIAL', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Maps to VendorCategory / AVL category for vendor-item matching.', max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('uom', models.CharField(help_text='Primary UOM e.g. NOS, KG, MTR', max_length=30)),
                ('secondary_uom', models.CharField(blank=True, help_text='Optional secondary UOM e.g. BOX when primary is NOS', max_length=30)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='qty_secondary = qty_primary × conversion_factor', max_digits=10, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('max_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In First Out'), ('WEIGHTED_AVG', 'Weighted Average')], default='FIFO', max_length=15)),
                ('is_batch_tracked', models.BooleanField(default=True, help_text='Track stock by batch/lot number')),
                ('is_serial_tracked', models.BooleanField(default=False, help_text='Each unit has a unique serial number (batch_number = serial no)')),
                ('drawing_number', models.CharField(blank=True, help_text='Engineering drawing reference number', max_length=100)),
                ('revision_number', models.CharField(blank=True, help_text='Drawing / BOM revision e.g. Rev A', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Link to sales Product master if this item is also sold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_type', models.CharField(choices=[('GRN', 'GRN Receipt Label'), ('ISSUE', 'Issue Slip Label'), ('TRANSFER', 'Transfer Label')], max_length=10)),
                ('reference_id', models.UUIDField(help_text='ID of the source document (GRN, IssueSlip, etc.)')),
                ('barcode_data', models.CharField(help_text='Scannable string: TENANT-ITEM-BATCH-SEQ', max_length=200, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_labels', to='inventory.itemmaster')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
