# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueslip',
            name='indent',
            field=models.ForeignKey(blank=True, help_text='Linked purchase indent if this issue was planned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_slips', to='purchase.purchaseindent'),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='materialissueslipitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='materialissueslipitem',
            name='slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialissueslip'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='grn',
            field=models.ForeignKey(blank=True, help_text='GRN that created this batch. Null for opening stock and manual entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='purchase.grn'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='materialissueslipitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='barcodelabel',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='materialissueslipitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['tenant', 'item_type'], name='inventory_i_tenant__8c1d71_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['tenant', 'category'], name='inventory_i_tenant__b74a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_i_tenant__ddc1e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemmaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_code'), name='unique_item_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='barcodelabel',
            index=models.Index(fields=['barcode_data'], name='inventory_b_barcode_c07ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodelabel',
            index=models.Index(fields=['reference_id'], name='inventory_b_referen_80a741_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_warehouse_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'zone', 'rack', 'shelf'), name='unique_bin_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['item', 'warehouse', '-created_at'], name='inventory_s_item_id_3475e0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_6e609d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['tenant', 'item', 'qc_status'], name='inventory_s_tenant__ddf2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_s_tenant__34919d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'batch_number', 'warehouse'), name='unique_batch_per_item_warehouse'),
        ),
    ]
