# Generated by Django 5.2.11 on 2026-06-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueslip',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this issue is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_slips', to='projects.project'),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of issued materials (sum of issued_qty × unit_cost)', max_digits=15),
        ),
    ]
