# Generated by Django 5.2.11 on 2026-06-24 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_materialissueslip_project_and_more'),
        ('mrp', '0001_initial'),
        ('projects', '0002_remove_project_bom_reference_project_bom'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Set by store manager. May be less than requested (partial approval).', max_digits=15, null=True)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, help_text='Cumulative qty consumed by issue slips against this reservation.', max_digits=15)),
                ('required_by_date', models.DateField(blank=True, help_text='Pulled from project.end_date on creation. Drives priority display.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('FULLY_ISSUED', 'Fully Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_reservations', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.itemmaster')),
                ('mrp_run', models.ForeignKey(blank=True, help_text='Set when auto-created by MRP run. Null for manual reservations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='mrp.mrprun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reservations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['required_by_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'item', 'status'], name='inventory_s_tenant__1e80ef_idx'), models.Index(fields=['tenant', 'project', 'status'], name='inventory_s_tenant__4fc568_idx')],
            },
        ),
    ]
