# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_approval_threshold', models.DecimalField(decimal_places=2, default=0, help_text='0 = all POs require GM approval regardless of value.', max_digits=15)),
                ('rfq_min_vendors', models.IntegerField(default=3)),
                ('grn_auto_qc', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Settings',
                'verbose_name_plural': 'Purchase Settings',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(blank=True, max_length=20)),
                ('legacy_vendor_code', models.CharField(blank=True, help_text='Vendor code from the previous ERP. Used for migration mapping.', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CONTRACTOR', 'Contractor'), ('SUBCONTRACTOR', 'Sub-Contractor'), ('SERVICE', 'Service Provider')], default='SUPPLIER', max_length=20)),
                ('category', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('RAW_MATERIAL', 'Raw Material'), ('CONSUMABLE', 'Consumable'), ('CIVIL', 'Civil'), ('IT', 'IT / Software'), ('LOGISTICS', 'Logistics / Transport'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=15)),
                ('msme_registered', models.BooleanField(default=False)),
                ('msme_number', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.TextField(blank=True, help_text='e.g. 30 days net, 50% advance + 50% against documents')),
                ('credit_days', models.IntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Vendor performance rating 0.00–5.00', max_digits=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedVendorList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_category', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('RAW_MATERIAL', 'Raw Material'), ('CONSUMABLE', 'Consumable'), ('CIVIL', 'Civil'), ('IT', 'IT / Software'), ('LOGISTICS', 'Logistics / Transport'), ('OTHER', 'Other')], max_length=20)),
                ('item_code', models.CharField(blank=True, help_text='Specific item code. Leave blank for category-level approval.', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avl_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avl_entries', to='vendors.vendor')),
            ],
            options={
                'ordering': ['item_category', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping')], default='BILLING', max_length=10)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gstin_for_address', models.CharField(blank=True, help_text='Branch GSTIN if different from main vendor GSTIN', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='vendors.vendor')),
            ],
            options={
                'ordering': ['address_type'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=15)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('CC', 'Cash Credit')], default='CURRENT', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GST_CERT', 'GST Certificate'), ('PAN', 'PAN Card'), ('MSME', 'MSME Certificate'), ('CANCELLED_CHEQUE', 'Cancelled Cheque'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='vendor_docs/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'status'], name='vendors_ven_tenant__928686_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'category'], name='vendors_ven_tenant__2e58f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'vendor_type'], name='vendors_ven_tenant__0681eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('tenant', 'vendor_code'), name='unique_vendor_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='approvedvendorlist',
            index=models.Index(fields=['tenant', 'item_category'], name='vendors_app_tenant__0c8ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvedvendorlist',
            index=models.Index(fields=['tenant', 'item_code'], name='vendors_app_tenant__539924_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvedvendorlist',
            constraint=models.UniqueConstraint(fields=('tenant', 'vendor', 'item_category', 'item_code'), name='unique_avl_entry_per_tenant'),
        ),
    ]
