# Generated by Django 5.2.11 on 2026-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='poc_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='POC Contact Number'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='POC Email'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='prospective_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prospective Value'),
        ),
    ]
