# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('accepted_qty', models.DecimalField(decimal_places=3, default=0, help_text='Set by QC after inspection', max_digits=15)),
                ('rejected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(max_length=30)),
                ('batch_number', models.CharField(blank=True, help_text='Assigned at GRN; auto-generated if blank', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseIndent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indent_number', models.CharField(blank=True, help_text='Auto-generated: MRN00001', max_length=20)),
                ('indent_type', models.CharField(choices=[('PRODUCTION', 'Production'), ('MAINTENANCE', 'Maintenance'), ('GENERAL', 'General'), ('PROJECT', 'Project / Contract')], default='PRODUCTION', max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('job_order_ref', models.CharField(blank=True, help_text='Production job order ref (future module)', max_length=100)),
                ('project_ref', models.CharField(blank=True, help_text='Project / contract ref for engineering orders', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseIndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('uom', models.CharField(max_length=30)),
                ('available_qty_at_time', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('fulfilled_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=10)),
                ('specifications', models.TextField(blank=True, help_text='Drawing revision, special requirements (engineering)')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=20)),
                ('po_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('delivery_address', models.JSONField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Vendor'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Project-specific T&C for engineering orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, help_text='Overrides item master description on the PO document')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_group_code', models.CharField(blank=True, max_length=50)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('drawing_ref', models.CharField(blank=True, help_text='Engineering drawing reference on PO line', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_number', models.CharField(blank=True, max_length=20)),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Vendors'), ('QUOTED', 'Quotations Received'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('uom', models.CharField(max_length=30)),
                ('specifications', models.TextField(blank=True)),
                ('drawing_ref', models.CharField(blank=True, help_text='Engineering drawing reference', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RFQVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RESPONDED', 'Responded'), ('NO_RESPONSE', 'No Response')], default='SENT', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text="Vendor's own invoice number", max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vendor_invoices/%Y/%m/')),
                ('match_status', models.CharField(choices=[('PENDING', 'Pending Match'), ('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('mismatch_notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Calculated from PO credit_days at creation', null=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, max_length=100)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('delivery_days', models.IntegerField(default=0)),
                ('payment_terms', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=15)),
                ('is_selected', models.BooleanField(default=False)),
                ('selection_justification', models.TextField(blank=True, help_text='Mandatory if selecting a vendor who is not the L1 (lowest price) bidder.')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('delivery_days', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, help_text='Import vs local distinction for engineering projects', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(blank=True, max_length=20)),
                ('received_date', models.DateField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('dc_number', models.CharField(blank=True, help_text='Vendor delivery challan number', max_length=100)),
                ('dc_date', models.DateField(blank=True, null=True)),
                ('dc_attachment', models.FileField(blank=True, null=True, upload_to='grn_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QC_PENDING', 'Pending QC'), ('QC_DONE', 'QC Completed'), ('STOCK_UPDATED', 'Stock Updated'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
