# Generated by Django 5.2.11 on 2026-05-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0001_initial'),
        ('tenants', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.grn'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Assigned after QC pass', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='purchaseindent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_indents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseindent',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_indents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseindent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseindentitem',
            name='indent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseindent'),
        ),
        migrations.AddField(
            model_name='purchaseindentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfq',
            name='indent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='purchase.purchaseindent'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchase.rfq'),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster'),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.rfq'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_vendors', to='purchase.rfq'),
        ),
        migrations.AddField(
            model_name='rfqvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchase.grn'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='purchase.rfq'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchase.vendorquotation'),
        ),
        migrations.AddField(
            model_name='vendorquotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.vendorquotation'),
        ),
        migrations.AddField(
            model_name='vendorquotationitem',
            name='rfq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.rfqitem'),
        ),
        migrations.AddConstraint(
            model_name='rfqvendor',
            constraint=models.UniqueConstraint(fields=('rfq', 'vendor'), name='unique_vendor_per_rfq'),
        ),
        migrations.AddConstraint(
            model_name='vendorquotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'vendor'), name='unique_quotation_per_rfq_vendor'),
        ),
    ]
