# Generated by Django 5.2.11 on 2026-06-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
        ('projects', '0002_remove_project_bom_reference_project_bom'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindent',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this indent is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='purchaseindentitem',
            name='mrp_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indent_items', to='mrp.mrpline'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this PO is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='projects.project'),
        ),
    ]
